version: '3.7'

services:
  maria_db:
    image: mariadb
    container_name: maria_db
    ports:
      - 3360:3306
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: unless-stopped
    volumes:
      - maria_db:/var/lib/mysql
      - ./dev/bt_test.sql:/docker-entrypoint-initdb.d/bt_test.sql:ro
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=bt_test
      - MYSQL_DATABASE=bt_test
      - MYSQL_USER=bt_test

  wataha:
    image: chajr/php56-nginx-extended
    container_name: bluetree
    volumes:
      - ./dev/log:/var/log/
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./source:/var/www/html
    ports:
      - 80:8080
    environment:
      - BLUETREE_DB_HOST=maria_db
      - BLUETREE_DB_USER=bt_test
      - BLUETREE_DB=bt_test
      - BLUETREE_DB_PASS=bt_test
      - BLUETREE_DB_PORT=3306
    depends_on:
      - maria_db

volumes:
  maria_db:
